# Makefile
SHELL   = /bin/bash
FILES   = luasc3.c
CC      = gcc
CFLAGS  = -g -DSYSV3 -pg -fPIC -DCOMPAT_MODULE

test:     xlsx.o expr.o Parser.o Lexer.o  luasc3.o util.o rpsc.h
	$(CC) $(CFLAGS) luasc3.o xlsx.o expr.o Parser.o Lexer.o util.o -lm `pkg-config --libs libxml-2.0  libzip lua5.2`
#	$(CC) -fPIC -shared -o sc.so luasc3.o

Lexer.c:	Lexer.l
	flex Lexer.l

Parser.c:	Parser.y Lexer.c
		bison -t Parser.y

xlsx.o:         xlsx.c
	$(CC) $(CFLAGS) -c  -D XLSX xlsx.c `pkg-config --cflags libxml-2.0`

%.o:            %.c rpsc.h
	$(CC) $(CFLAGS) -c $< -o $@ `pkg-config --cflags lua5.2`
                                                                                                               
clean:
	-rm -f *.o Lexer.c Parser.c Parser.h gmon.out test1
